# Generated by Django 4.2.2 on 2023-10-30 15:40

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(default=apps.accounts.models.get_default_image, upload_to='accounts/'),
        ),
    ]
