# Generated by Django 4.2.2 on 2023-10-29 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Publication title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Publication content')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time updated')),
                ('image', models.ImageField(default='no_image.png', upload_to='media/blog/', verbose_name='Publication image')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publication creator')),
            ],
        ),
    ]
