# Generated by Django 4.2.2 on 2023-10-30 15:40

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(default=apps.blog.models.get_default_image, upload_to='blog/', verbose_name='Publication image'),
        ),
    ]
